### ISSUE TITLE
Headers support

### ISSUE THREAD

**Issue by andrearossiavanade** [ponytailer/pydantic-client#45]
Would  be nice to be able also to add headers to the requests, both at initialization, shared between all the requests and at request level.
This would enable the possibility to call authenticated endpoints.

**Comment by ponytailer** [comment]
> Would be nice to be able also to add headers to the requests, both at initialization, shared between all the requests and at request level. This would enable the possibility to call authenticated endpoints.

OK. I'll add it later.

**Comment by ponytailer** [comment]
Add it #46 and release `v0.1.14`

**Comment by andrearossiavanade** [comment]
Thank you very much. When do you plan to release it to pypi?

**Comment by ponytailer** [comment]
> Thank you very much. When do you plan to release it to pypi?

done

**Comment by ponytailer** [comment]
> Thank you very much. When do you plan to release it to pypi?
> 
> 

And if it's helpful to you, stars it please. thank you
