### ISSUE TITLE
Calling method_info.func ?

### ISSUE THREAD

**Issue by benjaoming** [ponytailer/pydantic-client#61]
Hey!

Exciting pattern!

I was wondering if it could be possible to call back method_info.func to give some flexibility to construct the final object? i.e.

```python
class R(RequestsClient):

    @get("/books/{book_id}?query={query}")
    def get_book(self, book_id: int, query: str, response: Book) -> Book:
        book = response
        book.author = self.get_author(book.id)
        return book
```

I'm not sure if I'll need it yet :) It's of course easy to workaround by writing helper functions, i.e. this could be written:

```python
class R(RequestsClient):

    @get("/books/{book_id}?query={query}")
    def get_book(self, book_id: int, query: str) -> Book:
        ...

    def get_book_and_author(self, book_id: int, query: str) -> Book:
        book = self.get_book(book_id, query)
        book.author = self.get_author(book.id)
        return book
```

**Comment by ponytailer** [comment]
Yes, need the helper functions to do it.
`pydantic-client`  It mainly implements interaction with external interface layers. If it has its own business logic, it is best to package it with other functions.

but if you have other better ideas, tell me.

**Comment by ponytailer** [comment]
> Hey!
> 
> Exciting pattern!
> 
> I was wondering if it could be possible to call back method_info.func to give some flexibility to construct the final object? i.e.
> 
> ```python
> class R(RequestsClient):
> 
>     @get("/books/{book_id}?query={query}")
>     def get_book(self, book_id: int, query: str, response: Book) -> Book:
>         book = response
>         book.author = self.get_author(book.id)
>         return book
> ```
> 
> I'm not sure if I'll need it yet :) It's of course easy to workaround by writing helper functions, i.e. this could be written:
> 
> ```python
> class R(RequestsClient):
> 
>     @get("/books/{book_id}?query={query}")
>     def get_book(self, book_id: int, query: str) -> Book:
>         ...
> 
>     def get_book_and_author(self, book_id: int, query: str) -> Book:
>         book = self.get_book(book_id, query)
>         book.author = self.get_author(book.id)
>         return book
> ```

Yes, need the helper functions to do it.
`pydantic-client`  It mainly implements interaction with external interface layers. If it has its own business logic, it is best to package it with other functions.

but if you have other better ideas, tell me.

**Comment by benjaoming** [comment]
Thanks for the response!

Could there be other reasons to call the function itself? Otherwise, I guess I will close the issue :)

**Comment by ponytailer** [comment]
> Thanks for the response!
> 
> 
> 
> Could there be other reasons to call the function itself? Otherwise, I guess I will close the issue :)

> Thanks for the response!
> 
> Could there be other reasons to call the function itself? Otherwise, I guess I will close the issue :)

There is no special reason, just because it is relatively easy to implement. Let me think about your needs and see if it's possible to make minor modifications to achieve them.

**Comment by benjaoming** [comment]
@ponytailer maybe don't consider my needs, it was more of an example. I'm afraid I don't have a clever use case :)

There's a potential to use the function body for _something_ since it's just `...` and never called. But it could be doing something, for instance returning the final response - but in order to do that, it also needs the initial response as input.

**Comment by ponytailer** [comment]
> @ponytailer maybe don't consider my needs, it was more of an example. I'm afraid I don't have a clever use case :)
> 
> There's a potential to use the function body for _something_ since it's just `...` and never called. But it could be doing something, for instance returning the final response - but in order to do that, it also needs the initial response as input.

Thank you for your suggestion. My implementation method may not be very good. My original intention was to write an httpclient similar to 'Retrofit' that can easily format the return value of external services.
So I decided to reorganize the code structure to better understand it when using it.
