### ISSUE TITLE
Allow injection of aiohttp ClientSession

### ISSUE THREAD

**Issue by DefiDebauchery** [ponytailer/pydantic-client#71]
Hello! I appreciate the relatively no-nonsense approach to making an API Client.

I have need to use my own aiohttp ClientSession, which could define its own proxy settings, timeout configuration, and even default headers - which would be lost, as `pydantic-client` assumes a fresh session.

Would it be possible to have the ability to pass in an existing session to `ClientConfig`?

**Comment by ponytailer** [comment]
> Hello! I appreciate the relatively no-nonsense approach to making an API Client.
> 
> 
> 
> I have need to use my own aiohttp ClientSession, which could define its own proxy settings, timeout configuration, and even default headers - which would be lost, as `pydantic-client` assumes a fresh session.
> 
> 
> 
> Would it be possible to have the ability to pass in an existing session to `ClientConfig`?

Thank you for your attention. I will modify the code according to your needs during my free time, or you can also submit a pull request yourself.

**Comment by ponytailer** [comment]
Thank you for your suggestion and your star.
