### ISSUE TITLE
Support for files

### ISSUE THREAD

**Issue by garrettrathbone** [ponytailer/pydantic-client#74]
Sending files via an object currently seems to be unsupported. It would be simple enough to pull the file into the files param for the request, but unsure how we'd even relay that via the object. Thought it would be smart to open a ticket to start the conversation.

**Comment by ponytailer** [comment]
> Sending files via an object currently seems to be unsupported. It would be simple enough to pull the file into the files param for the request, but unsure how we'd even relay that via the object. Thought it would be smart to open a ticket to start the conversation.

Thank you for your suggestion. But if it is a file, the normal interface return value would be `FileResponse`, `pydantic-client` usually only applies to `JsonResponse`.

**Comment by ponytailer** [comment]
And now it had been supported it. you can see the history log.
```python
@post("/download")
def get_file(self) -> File:
   ...

```
